'''get walls in revit file'''

#Imports
import rpw
from Autodesk.Revit.DB import Element, Transaction

doc = __revit__.ActiveUIDocument.Document
uidoc = __revit__.ActiveUIDocument
t = Transaction(doc, 'Set Parameter by Name')


cl = FilteredElementCollector(doc) #grabs document 
walls = cl.OfCategory(BuiltInCategory.OST_Walls).WhereElementIsNotElementType() #grabs and filters for walls

#t.Start()

#for x in walls: 
	#if x.LookupParameter("Top Offset").AsValueString() != "0\' - 0\"": #filters for walls not equalling to 0
	#	x.LookupParameter("Top Offset").SetValue("0\' - 0\"")
for x in walls:
 	if x.LookupParameter("Top Offset").AsValueString() != "0\' - 0\"":
 		#x.get_Parameter(BuiltInParameter.WALL_TOP_OFFSET).Set("0\' - 0\"")
 		x.LookupParameter("Top Offset").Set(0)



#End Transaction
#t.Commit()
		
		#print(x.LookupParameter("Top Offset").AsValueString()) #prints out top offset string not equal to 0
		#x.GetParemeter("Top Offset").SetValue("0")
		
		
'''
element = db.Element.from_int(952467)
>>> element
﻿<rpw:Wall [symbol:Generic - 3"] [id:952467]>
>>> element.get_wall_type
﻿<bound method Wall.get_wall_type of <rpw:Wall [symbol:Generic - 3"] [id:952467]>>
>>> element.parameters['Top Offset'].value
﻿4.0

element = db.Element.from_int(352690)
with db.Transaction('Change Comment Wall'):
     element.parameters['Comments'].value = 'Something new'
     
with db.Transaction('Change height'):
	element.parameters['Top Offset'].value = 10 
 


'''

'''
import rpw
from rpw import revit, db, ui, DB, UI

element = db.Element.from_int(352690)
with db.Transaction('Change height'):
    element.parameters['Top Offset'].value = 10 

# wall top constraint needs ot be set to a level. Cannot be unconnected. 
'''

'''
import clr
clr.AddReference('RevitAPI') 
clr.AddReference('RevitAPIUI') 
from Autodesk.Revit.DB import * 
from Autodesk.Revit.UI import *
app = __revit__.Application
doc = __revit__.ActiveUIDocument.Document
ui = __revit__.ActiveUIDocument

element = doc.GetElement(ElementId(352690))

t = Transaction (doc, 'Change Height')
t.Start()
parameter = element.GetParameters('Top Offset')[0]
parameter.Set(10)   
t.Commit()
'''
